language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt 
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - pytest --cov=ims_api/app/
after_success:
  - coveralls
