language: python
python:
  - "3.6"

services:
  - postgresql

env:
  global:
    - CC_TEST_REPORTER_ID=$reporter_id

before_script:
  - export DB_NAME='ims_db'
  - export DB_USER='postgres'
  - psql -c 'create database ims_db;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
  - export CC_TEST_REPORTER_ID=$reporter_id
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  - py.test --cov=ims_api/app

after_success:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - coveralls
