# Generated by Django 2.2.5 on 2019-11-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('profile_pic', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_role', models.CharField(db_index=True, default='admin', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('profile_pic', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('user_role', models.CharField(db_index=True, default='normal_user', max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
