# Generated by Django 2.2.5 on 2019-10-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user_role',
            field=models.CharField(db_index=True, default='admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(db_index=True, default='normal_user', max_length=255),
        ),
    ]
